name: Daily Location Count

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 17 * * *"  # 매일 오후 5시 (KST 기준 새벽 2시)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - uses: actions/checkout@v4

      # 2. Python 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3. Chrome 및 ChromeDriver 설치
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # 4. Python 패키지 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 lxml selenium webdriver_manager

      # 5. 스타벅스 기본 정보 수집 (전국 매장, 약 40분)
      - name: Run Starbucks Count Script
        run: |
          python starbucks-count.py

      # 6. 생성된 데이터 파일 커밋
      - name: Commit changes
        run: |
          git config --global user.email "webstoryboy@naver.com"
          git config --global user.name "websseu"
          git add location/ || echo "No files to add"
          git commit -m "스타벅스 위치 데이터 업데이트 - $(date +"%Y-%m-%d")" || echo "No changes to commit"

      # 7. 변경사항 푸시
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}

